---
Analyzer:
  MaxNbr: "999"  # up to 999
Samples:
  MaxNbr: "65535" # up to 2^16-1 (65535)
Inspector:
  Sample:
    DataShift:
      Enable:           true
      BitShiftMin:      "-2"
      BitShiftMax:      "2"
    Bit:
      Enable:           true
    Integer:
      Enable:           true
      MaxTruncatedBits: "-1"
      MaxRoundedBits:   "-1"
      MaxAbsDiff:       "-1"
  Segment:
    SampleShift:
      Enable:           true
      SampleShiftMin:   "-2"
      SampleShiftMax:   "2"
      ByteShiftMin:     "-3"
      ByteShiftMax:     "3"
    Statistic:
      Enable:           true
    Range:
      Enable:           true
Dump:
  FileFstEnable:     true
  FileFstName:       "eaInspectorWaves.fst"
  FileVcdEnable:     true
  FileVcdName:       "eaInspectorWaves.vcd"
  FailAnalzerOnly:   false
  FailInspectorOnly: false
Log:
  ToConsoleEnable:     true
  ConsoleVerbosity:    "EA_VERBOSITY_LEVEL_LOW" # EA_VERBOSITY_LEVEL_LOW
  ConsoleColorsEnable: true
  ToSimConsoleEnable:  false
  ToFileEnable:        true
  FileVerbosity:       "EA_VERBOSITY_LEVEL_FULL" # (EA_VERBOSITY_LEVEL_FULL)
  FileName:            "eaLogFile.log"
  ReportPathEnable: true
  SumSkipPass:         true
Report:
  PosPercLimit:      "50.0"
  SummaryDumpEnable: true
  SummaryFilename:   "eaAnalyzerSummary.csv"
  SummaryIncremental: false
  DatabaseFilename:  "eaDatabase.yaml"
  DatabaseDumpEnable: true
  
